import NavBar from '@/ui/Navigation/NavBar'
import './globals.css'
import { Inter } from 'next/font/google'
import Providers from '@/lib/providers'
import Script from 'next/script'
import Footer from '@/ui/Navigation/Footer'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <Script src='https://cdn.jsdelivr.net/npm/vanta@0.5.24/dist/vanta.globe.min.js' />

      <body className=''>
        <Providers>
          <NavBar />
          {children}
          <Footer />
        </Providers></body>
    </html>
  )
}
