export const allGenres = [
  'Afrobeat',
  'Afro-Jazz',
  'Afro-Pop',
  'Afrobeats',
  'Alternative Hip Hop',
  'Alternative Rock',
  'Ambient',
  'Americana',
  'Arabic Music',
  'Asian Music',
  'Australian Music',
  'Bebop',
  'Big Band',
  'Bluegrass',
  'Bossanova',
  'Brazilian Jazz',
  'Breakbeat',
  'Cajun',
  'Calypso',
  'Classic Country',
  'Classic Rock',
  'Conscious Hip Hop',
  'Country',
  'Country Gospel',
  'Country-Pop',
  'Country-Rock',
  'Dance-Pop',
  'Dub',
  'Dub Poetry',
  'Electronic',
  'Flamenco',
  'Funk',
  'Fusion',
  'Gangsta Rap',
  'Garage Rock',
  'Grindcore',
  'Grunge',
  'Hard Bop',
  'Hard Rock',
  'Hip Hop/Rap',
  'Honky Tonk',
  'House',
  'Indian Music',
  'Indie Rock',
  'Irish Folk',
  'Jazz',
  'Jersey Club',
  'Latin Jazz',
  'Latin Music',
  'Lo-Fi',
  'Lovers Rock',
  'Middle Eastern Music',
  'Motown',
  'Neo-Soul',
  'New Wave',
  'Native American Music',
  'Outlaw Country',
  'Power Pop',
  'Progressive Rock',
  'Psychedelic Rock',
  'Punk Rock',
  'Quiet Storm',
  'R&B',
  'Red Dirt',
  'Reggae',

  'Rock',
  'Roots Reggae',
  'Samba',
  'Smooth Jazz',
  'Soft Rock',
  'Soca',
  'Southern Hip Hop',
  'Southern Rock',
  'Sophisti-Pop',
  'Soul',
  'Synth-Pop',
  'Synthwave',
  'Swing',
  'Techno',
  'Trance',
  'Trap',
  'Zouk'
];
